import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  final SharedPreferences _prefs;
  String _currentLanguage = 'en';

  // Translation maps
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'home': 'Home',
      'forecast': 'Forecast',
      'cities': 'Cities',
      'settings': 'Settings',
      'search_location': 'Search Location',
      'search_city': 'Search for a city...',
      'current_weather': 'Current Weather',
      'rain_forecast': 'Next Hour Rain Forecast',
      'seven_day_forecast': '7-Day Forecast',
      'saved_cities': 'Saved Cities',
      'add_city': 'Add City',
      'temperature_unit': 'Temperature Unit',
      'wind_speed_unit': 'Wind Speed Unit',
      'rain_alerts': 'Rain Alerts',
      'weather_updates': 'Weather Updates',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'about': 'About',
      'share_app': 'Share App',
      'clear_data': 'Clear Data',
      'celsius': 'Celsius',
      'fahrenheit': 'Fahrenheit',
      'kmh': 'km/h',
      'mph': 'mph',
      'ms': 'm/s',
      'english': 'English',
      'spanish': 'Spanish',
      'french': 'French',
      'german': 'German',
      'chinese': 'Chinese',
      'arabic': 'Arabic',
      'humidity': 'Humidity',
      'wind': 'Wind',
      'pressure': 'Pressure',
      'updated_now': 'Updated just now',
      'rain_expected': 'Rain Expected',
      'rain_expected_desc': 'Light rain is expected in the next hour.',
      'no_rain_expected': 'No rain expected in the next hour',
      'enable_location': 'Enable Location',
      'location_required': 'Location access required',
      'try_again': 'Try Again',
      'loading': 'Loading...',
      'error_loading_weather': 'Error loading weather data',
      'error_loading_forecast': 'Error loading forecast data',
      'refresh': 'Refresh',
      'today': 'Today',
      'tomorrow': 'Tomorrow',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
    },
    'es': {
      'home': 'Inicio',
      'forecast': 'Pronóstico',
      'cities': 'Ciudades',
      'settings': 'Configuración',
      'search_location': 'Buscar Ubicación',
      'search_city': 'Buscar una ciudad...',
      'current_weather': 'Tiempo Actual',
      'rain_forecast': 'Pronóstico de Lluvia de la Próxima Hora',
      'seven_day_forecast': 'Pronóstico de 7 Días',
      'saved_cities': 'Ciudades Guardadas',
      'add_city': 'Agregar Ciudad',
      'temperature_unit': 'Unidad de Temperatura',
      'wind_speed_unit': 'Unidad de Velocidad del Viento',
      'rain_alerts': 'Alertas de Lluvia',
      'weather_updates': 'Actualizaciones del Tiempo',
      'dark_mode': 'Modo Oscuro',
      'language': 'Idioma',
      'about': 'Acerca de',
      'share_app': 'Compartir App',
      'clear_data': 'Limpiar Datos',
      'celsius': 'Celsius',
      'fahrenheit': 'Fahrenheit',
      'kmh': 'km/h',
      'mph': 'mph',
      'ms': 'm/s',
      'english': 'Inglés',
      'spanish': 'Español',
      'french': 'Francés',
      'german': 'Alemán',
      'chinese': 'Chino',
      'arabic': 'Árabe',
      'humidity': 'Humedad',
      'wind': 'Viento',
      'pressure': 'Presión',
      'updated_now': 'Actualizado ahora',
      'rain_expected': 'Se Espera Lluvia',
      'rain_expected_desc': 'Se espera lluvia ligera en la próxima hora.',
      'no_rain_expected': 'No se espera lluvia en la próxima hora',
      'enable_location': 'Habilitar Ubicación',
      'location_required': 'Se requiere acceso a la ubicación',
      'try_again': 'Intentar de Nuevo',
      'loading': 'Cargando...',
      'error_loading_weather': 'Error al cargar datos del tiempo',
      'error_loading_forecast': 'Error al cargar datos del pronóstico',
      'refresh': 'Actualizar',
      'today': 'Hoy',
      'tomorrow': 'Mañana',
      'monday': 'Lunes',
      'tuesday': 'Martes',
      'wednesday': 'Miércoles',
      'thursday': 'Jueves',
      'friday': 'Viernes',
      'saturday': 'Sábado',
      'sunday': 'Domingo',
    },
    'fr': {
      'home': 'Accueil',
      'forecast': 'Prévisions',
      'cities': 'Villes',
      'settings': 'Paramètres',
      'search_location': 'Rechercher un lieu',
      'search_city': 'Rechercher une ville...',
      'current_weather': 'Météo actuelle',
      'rain_forecast': 'Prévisions de pluie pour la prochaine heure',
      'seven_day_forecast': 'Prévisions sur 7 jours',
      'saved_cities': 'Villes sauvegardées',
      'add_city': 'Ajouter une ville',
      'temperature_unit': 'Unité de température',
      'wind_speed_unit': 'Unité de vitesse du vent',
      'rain_alerts': 'Alertes pluie',
      'weather_updates': 'Mises à jour météo',
      'dark_mode': 'Mode sombre',
      'language': 'Langue',
      'about': 'À propos',
      'share_app': 'Partager l\'application',
      'clear_data': 'Effacer les données',
      'celsius': 'Celsius',
      'fahrenheit': 'Fahrenheit',
      'kmh': 'km/h',
      'mph': 'mph',
      'ms': 'm/s',
      'english': 'Anglais',
      'spanish': 'Espagnol',
      'french': 'Français',
      'german': 'Allemand',
      'chinese': 'Chinois',
      'arabic': 'Arabe',
      'humidity': 'Humidité',
      'wind': 'Vent',
      'pressure': 'Pression',
      'updated_now': 'Mis à jour à l\'instant',
      'rain_expected': 'Pluie prévue',
      'rain_expected_desc': 'Une légère pluie est prévue dans l\'heure à venir.',
      'no_rain_expected': 'Pas de pluie prévue dans l\'heure à venir',
      'enable_location': 'Activer la localisation',
      'location_required': 'Accès à la localisation requis',
      'try_again': 'Réessayer',
      'loading': 'Chargement...',
      'error_loading_weather': 'Erreur lors du chargement des données météo',
      'error_loading_forecast': 'Erreur lors du chargement des prévisions',
      'refresh': 'Actualiser',
      'today': 'Aujourd\'hui',
      'tomorrow': 'Demain',
      'monday': 'Lundi',
      'tuesday': 'Mardi',
      'wednesday': 'Mercredi',
      'thursday': 'Jeudi',
      'friday': 'Vendredi',
      'saturday': 'Samedi',
      'sunday': 'Dimanche',
    },
    'de': {
      'home': 'Startseite',
      'forecast': 'Vorhersage',
      'cities': 'Städte',
      'settings': 'Einstellungen',
      'search_location': 'Ort suchen',
      'search_city': 'Suche nach einer Stadt...',
      'current_weather': 'Aktuelles Wetter',
      'rain_forecast': 'Regenvorhersage für die nächste Stunde',
      'seven_day_forecast': '7-Tage-Vorhersage',
      'saved_cities': 'Gespeicherte Städte',
      'add_city': 'Stadt hinzufügen',
      'temperature_unit': 'Temperatureinheit',
      'wind_speed_unit': 'Windgeschwindigkeitseinheit',
      'rain_alerts': 'Regenwarnungen',
      'weather_updates': 'Wetteraktualisierungen',
      'dark_mode': 'Dunkler Modus',
      'language': 'Sprache',
      'about': 'Über',
      'share_app': 'App teilen',
      'clear_data': 'Daten löschen',
      'celsius': 'Celsius',
      'fahrenheit': 'Fahrenheit',
      'kmh': 'km/h',
      'mph': 'mph',
      'ms': 'm/s',
      'english': 'Englisch',
      'spanish': 'Spanisch',
      'french': 'Französisch',
      'german': 'Deutsch',
      'chinese': 'Chinesisch',
      'arabic': 'Arabisch',
      'humidity': 'Luftfeuchtigkeit',
      'wind': 'Wind',
      'pressure': 'Luftdruck',
      'updated_now': 'Gerade aktualisiert',
      'rain_expected': 'Regen erwartet',
      'rain_expected_desc': 'Leichter Regen wird in der nächsten Stunde erwartet.',
      'no_rain_expected': 'Kein Regen in der nächsten Stunde erwartet',
      'enable_location': 'Standort aktivieren',
      'location_required': 'Standortzugriff erforderlich',
      'try_again': 'Erneut versuchen',
      'loading': 'Lädt...',
      'error_loading_weather': 'Fehler beim Laden der Wetterdaten',
      'error_loading_forecast': 'Fehler beim Laden der Vorhersagedaten',
      'refresh': 'Aktualisieren',
      'today': 'Heute',
      'tomorrow': 'Morgen',
      'monday': 'Montag',
      'tuesday': 'Dienstag',
      'wednesday': 'Mittwoch',
      'thursday': 'Donnerstag',
      'friday': 'Freitag',
      'saturday': 'Samstag',
      'sunday': 'Sonntag',
    },

    'zh': {
      'home': '首页',
      'forecast': '天气预报',
      'cities': '城市',
      'settings': '设置',
      'search_location': '搜索位置',
      'search_city': '搜索城市...',
      'current_weather': '当前天气',
      'rain_forecast': '未来一小时降雨预测',
      'seven_day_forecast': '7天天气预报',
      'saved_cities': '已保存的城市',
      'add_city': '添加城市',
      'temperature_unit': '温度单位',
      'wind_speed_unit': '风速单位',
      'rain_alerts': '降雨提醒',
      'weather_updates': '天气更新',
      'dark_mode': '深色模式',
      'language': '语言',
      'about': '关于',
      'share_app': '分享应用',
      'clear_data': '清除数据',
      'celsius': '摄氏度',
      'fahrenheit': '华氏度',
      'kmh': '公里/小时',
      'mph': '英里/小时',
      'ms': '米/秒',
      'english': '英语',
      'spanish': '西班牙语',
      'french': '法语',
      'german': '德语',
      'chinese': '中文',
      'arabic': '阿拉伯语',
      'humidity': '湿度',
      'wind': '风速',
      'pressure': '气压',
      'updated_now': '刚刚更新',
      'rain_expected': '预计降雨',
      'rain_expected_desc': '未来一小时预计有小雨。',
      'no_rain_expected': '未来一小时无降雨',
      'enable_location': '启用位置',
      'location_required': '需要位置权限',
      'try_again': '重试',
      'loading': '加载中...',
      'error_loading_weather': '加载天气数据出错',
      'error_loading_forecast': '加载预报数据出错',
      'refresh': '刷新',
      'today': '今天',
      'tomorrow': '明天',
      'monday': '星期一',
      'tuesday': '星期二',
      'wednesday': '星期三',
      'thursday': '星期四',
      'friday': '星期五',
      'saturday': '星期六',
      'sunday': '星期日',
    },
    'ar': {
      'home': 'الرئيسية',
      'forecast': 'التنبؤات',
      'cities': 'المدن',
      'settings': 'الإعدادات',
      'search_location': 'ابحث عن موقع',
      'search_city': 'ابحث عن مدينة...',
      'current_weather': 'الطقس الحالي',
      'rain_forecast': 'توقعات هطول الأمطار للساعة القادمة',
      'seven_day_forecast': 'توقعات الطقس لسبعة أيام',
      'saved_cities': 'المدن المحفوظة',
      'add_city': 'إضافة مدينة',
      'temperature_unit': 'وحدة درجة الحرارة',
      'wind_speed_unit': 'وحدة سرعة الرياح',
      'rain_alerts': 'تنبيهات المطر',
      'weather_updates': 'تحديثات الطقس',
      'dark_mode': 'الوضع الداكن',
      'language': 'اللغة',
      'about': 'حول التطبيق',
      'share_app': 'مشاركة التطبيق',
      'clear_data': 'مسح البيانات',
      'celsius': 'درجة مئوية',
      'fahrenheit': 'فهرنهايت',
      'kmh': 'كم/س',
      'mph': 'ميل/س',
      'ms': 'م/ث',
      'english': 'الإنجليزية',
      'spanish': 'الإسبانية',
      'french': 'الفرنسية',
      'german': 'الألمانية',
      'chinese': 'الصينية',
      'arabic': 'العربية',
      'humidity': 'الرطوبة',
      'wind': 'الرياح',
      'pressure': 'الضغط',
      'updated_now': 'تم التحديث الآن',
      'rain_expected': 'توقع هطول المطر',
      'rain_expected_desc': 'من المتوقع هطول أمطار خفيفة في الساعة القادمة.',
      'no_rain_expected': 'لا يُتوقع هطول أمطار في الساعة القادمة',
      'enable_location': 'تفعيل الموقع',
      'location_required': 'الوصول إلى الموقع مطلوب',
      'try_again': 'حاول مرة أخرى',
      'loading': 'جارٍ التحميل...',
      'error_loading_weather': 'حدث خطأ أثناء تحميل بيانات الطقس',
      'error_loading_forecast': 'حدث خطأ أثناء تحميل بيانات التنبؤ',
      'refresh': 'تحديث',
      'today': 'اليوم',
      'tomorrow': 'غداً',
      'monday': 'الاثنين',
      'tuesday': 'الثلاثاء',
      'wednesday': 'الأربعاء',
      'thursday': 'الخميس',
      'friday': 'الجمعة',
      'saturday': 'السبت',
      'sunday': 'الأحد',
    },


  };

  LanguageProvider(this._prefs) {
    loadLanguage();
  }

  String get currentLanguage => _currentLanguage;

  Future<void> loadLanguage() async {
    _currentLanguage = _prefs.getString('language') ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String languageCode) async {
    if (_currentLanguage != languageCode) {
      _currentLanguage = languageCode;
      await _prefs.setString('language', languageCode);
      notifyListeners();
    }
  }

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? 
           _translations['en']?[key] ?? 
           key;
  }

  String t(String key) => translate(key);
}